In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
import sklearn

In [2]:
data = pd.read_csv("C:/Users/Biggest/Downloads/OLX_cars_dataset00.csv")

In [3]:
data.head()

Ad ID                               Car Name      Make  Model  Year  \
0  1079071571           fresh import Passo 2021model    Toyota  Passo  2021   
1  1080125520                            Suzuki ravi    Suzuki   Ravi  2018   
2  1080748789  Suzuki bolan 2015 contact 03112271054    Suzuki  Bolan  2015   
3  1076081635                     Diahatsu Move 2013  Daihatsu   Move  2013   
4  1080812928     Suzuki Swift DLX 2011 miner tuchap    Suzuki  Swift  2011   

   KM's driven    Price    Fuel Registration city Car documents  Assembly  \
0        54000  4190000  Petrol      Unregistered      Original  Imported   
1        95000  1300000  Petrol           Karachi      Original     Local   
2        50000   800000  Petrol           Karachi      Original     Local   
3        94000  2155000  Petrol            Lahore      Original  Imported   
4       126544  1440000  Petrol           Karachi      Original     Local   

  Transmission Condition            Seller Location  \
0    Automatic      Used  Airline Avenue, Islamabad   
1       Manual      Used         Kahuta, Rawalpindi   
2       Manual      Used  Lyari Expressway, Karachi   
3    Automatic      Used      New Amir Town, Lahore   
4       Manual      Used         Shadman 2, Karachi   

                                         Description  \
0  it's 2021 model fresh import, perfect engine s...   
1                              Suzuki ravi 2018 col    
2  Suzuki bolan model 2015 reg 2022 ghadi me koi ...   
3  Move Push start \nHome Used car. \nModel 2013....   
4  Suzuki Swift DLX\nAbS Break 100%\nengine 100%\...   

                                        Car Features  \
0  ABS, Air Bags, AM/FM Radio, CD Player, Cassett...   
1                                        AM/FM Radio   
2                                      Rear speakers   
3  ABS, Air Bags, Air Conditioning, Alloy Rims, A...   
4  ABS, Air Conditioning, Alloy Rims, AM/FM Radio...   

                                        Images URL's  \
0  ['https://images.olx.com.pk/thumbnails/4039460...   
1  ['https://images.olx.com.pk/thumbnails/4102504...   
2  ['https://images.olx.com.pk/thumbnails/4139520...   
3  ['https://images.olx.com.pk/thumbnails/3865337...   
4  ['https://images.olx.com.pk/thumbnails/4143509...   

                                         Car Profile  
0  https://www.olx.com.pk/item/fresh-import-passo...  
1  https://www.olx.com.pk/item/suzuki-ravi-iid-10...  
2  https://www.olx.com.pk/item/suzuki-bolan-2015-...  
3  https://www.olx.com.pk/item/diahatsu-move-2013...  
4  https://www.olx.com.pk/item/suzuki-swift-dlx-2...

In [4]:
from datetime import date
date.today().year
data['Car_Age']=date.today().year-data['Year']
data.head()

Ad ID                               Car Name      Make  Model  Year  \
0  1079071571           fresh import Passo 2021model    Toyota  Passo  2021   
1  1080125520                            Suzuki ravi    Suzuki   Ravi  2018   
2  1080748789  Suzuki bolan 2015 contact 03112271054    Suzuki  Bolan  2015   
3  1076081635                     Diahatsu Move 2013  Daihatsu   Move  2013   
4  1080812928     Suzuki Swift DLX 2011 miner tuchap    Suzuki  Swift  2011   

   KM's driven    Price    Fuel Registration city Car documents  Assembly  \
0        54000  4190000  Petrol      Unregistered      Original  Imported   
1        95000  1300000  Petrol           Karachi      Original     Local   
2        50000   800000  Petrol           Karachi      Original     Local   
3        94000  2155000  Petrol            Lahore      Original  Imported   
4       126544  1440000  Petrol           Karachi      Original     Local   

  Transmission Condition            Seller Location  \
0    Automatic      Used  Airline Avenue, Islamabad   
1       Manual      Used         Kahuta, Rawalpindi   
2       Manual      Used  Lyari Expressway, Karachi   
3    Automatic      Used      New Amir Town, Lahore   
4       Manual      Used         Shadman 2, Karachi   

                                         Description  \
0  it's 2021 model fresh import, perfect engine s...   
1                              Suzuki ravi 2018 col    
2  Suzuki bolan model 2015 reg 2022 ghadi me koi ...   
3  Move Push start \nHome Used car. \nModel 2013....   
4  Suzuki Swift DLX\nAbS Break 100%\nengine 100%\...   

                                        Car Features  \
0  ABS, Air Bags, AM/FM Radio, CD Player, Cassett...   
1                                        AM/FM Radio   
2                                      Rear speakers   
3  ABS, Air Bags, Air Conditioning, Alloy Rims, A...   
4  ABS, Air Conditioning, Alloy Rims, AM/FM Radio...   

                                        Images URL's  \
0  ['https://images.olx.com.pk/thumbnails/4039460...   
1  ['https://images.olx.com.pk/thumbnails/4102504...   
2  ['https://images.olx.com.pk/thumbnails/4139520...   
3  ['https://images.olx.com.pk/thumbnails/3865337...   
4  ['https://images.olx.com.pk/thumbnails/4143509...   

                                         Car Profile  Car_Age  
0  https://www.olx.com.pk/item/fresh-import-passo...        3  
1  https://www.olx.com.pk/item/suzuki-ravi-iid-10...        6  
2  https://www.olx.com.pk/item/suzuki-bolan-2015-...        9  
3  https://www.olx.com.pk/item/diahatsu-move-2013...       11  
4  https://www.olx.com.pk/item/suzuki-swift-dlx-2...       13

In [6]:
# create a new colunm for car feature count - tells the number of features each car has.

data['Car_Features_count'] = data['Car Features'].str.split(',').apply(len)


data.head()

Ad ID                               Car Name      Make  Model  Year  \
0  1079071571           fresh import Passo 2021model    Toyota  Passo  2021   
1  1080125520                            Suzuki ravi    Suzuki   Ravi  2018   
2  1080748789  Suzuki bolan 2015 contact 03112271054    Suzuki  Bolan  2015   
3  1076081635                     Diahatsu Move 2013  Daihatsu   Move  2013   
4  1080812928     Suzuki Swift DLX 2011 miner tuchap    Suzuki  Swift  2011   

   KM's driven    Price    Fuel Registration city Car documents  Assembly  \
0        54000  4190000  Petrol      Unregistered      Original  Imported   
1        95000  1300000  Petrol           Karachi      Original     Local   
2        50000   800000  Petrol           Karachi      Original     Local   
3        94000  2155000  Petrol            Lahore      Original  Imported   
4       126544  1440000  Petrol           Karachi      Original     Local   

  Transmission Condition            Seller Location  \
0    Automatic      Used  Airline Avenue, Islamabad   
1       Manual      Used         Kahuta, Rawalpindi   
2       Manual      Used  Lyari Expressway, Karachi   
3    Automatic      Used      New Amir Town, Lahore   
4       Manual      Used         Shadman 2, Karachi   

                                         Description  \
0  it's 2021 model fresh import, perfect engine s...   
1                              Suzuki ravi 2018 col    
2  Suzuki bolan model 2015 reg 2022 ghadi me koi ...   
3  Move Push start \nHome Used car. \nModel 2013....   
4  Suzuki Swift DLX\nAbS Break 100%\nengine 100%\...   

                                        Car Features  \
0  ABS, Air Bags, AM/FM Radio, CD Player, Cassett...   
1                                        AM/FM Radio   
2                                      Rear speakers   
3  ABS, Air Bags, Air Conditioning, Alloy Rims, A...   
4  ABS, Air Conditioning, Alloy Rims, AM/FM Radio...   

                                        Images URL's  \
0  ['https://images.olx.com.pk/thumbnails/4039460...   
1  ['https://images.olx.com.pk/thumbnails/4102504...   
2  ['https://images.olx.com.pk/thumbnails/4139520...   
3  ['https://images.olx.com.pk/thumbnails/3865337...   
4  ['https://images.olx.com.pk/thumbnails/4143509...   

                                         Car Profile  Car_Age  \
0  https://www.olx.com.pk/item/fresh-import-passo...        3   
1  https://www.olx.com.pk/item/suzuki-ravi-iid-10...        6   
2  https://www.olx.com.pk/item/suzuki-bolan-2015-...        9   
3  https://www.olx.com.pk/item/diahatsu-move-2013...       11   
4  https://www.olx.com.pk/item/suzuki-swift-dlx-2...       13   

   Car_Features_count  
0                  18  
1                   1  
2                   1  
3                  12  
4                   8

In [7]:
x = data[["KM's driven", 'Car_Age', 'Car_Features_count']]
y = data['Price']

In [8]:
x

KM's driven  Car_Age  Car_Features_count
0           54000        3                  18
1           95000        6                   1
2           50000        9                   1
3           94000       11                  12
4          126544       13                   8
...           ...      ...                 ...
9174       115000       10                  20
9175       100000        7                   5
9176       123456       23                   8
9177        89000       15                  12
9178        95000        8                  25

[9179 rows x 3 columns]

In [9]:
y

0       4190000
1       1300000
2        800000
3       2155000
4       1440000
         ...   
9174    2725000
9175    1850000
9176    1100000
9177     970000
9178    2050000
Name: Price, Length: 9179, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size = 0.2, random_state = 0)

In [12]:
x_train

KM's driven  Car_Age  Car_Features_count
2784        54800        9                  21
713         18000       20                   4
1235        30000        3                  12
8947        95655        8                   4
5543       120792       18                  12
...           ...      ...                 ...
4373        69000        8                  13
7891       130000       19                  16
4859        50000        6                   2
3264        45000       24                   2
2732       150000       18                   1

[7343 rows x 3 columns]

In [13]:
y_test

8359    1150000
3844    2100000
3896    3475000
7630     900000
5341    3850000
         ...   
655     1415000
6271    4575000
445     2200000
5687    2695000
660      630000
Name: Price, Length: 1836, dtype: int64

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
stndrd = StandardScaler()
x_train = stndrd.fit_transform(x_train)
x_test = stndrd.transform(x_test)

In [16]:
x_train

array([[-0.66725807, -0.44629915,  2.11568312],
       [-1.25958308,  1.36931009, -0.75824871],
       [-1.06643362, -1.43663146,  0.5941898 ],
       ...,
       [-0.74451786, -0.94146531, -1.09635834],
       [-0.8249968 ,  2.02953163, -1.09635834],
       [ 0.86506096,  1.03919932, -1.26541315]])

In [17]:
x_test

array([[-1.35060476,  0.54403316,  0.25608017],
       [-0.10068633, -0.94146531, -1.26541315],
       [ 0.02807998, -0.11618838,  2.28473793],
       ...,
       [ 0.46266626,  0.54403316,  1.10135424],
       [ 0.86506096,  0.21392239,  1.10135424],
       [-0.66403891,  1.36931009, -1.26541315]])

In [18]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [19]:
model.fit(x_train,y_train)

LinearRegression()

In [21]:
model.predict(x_test)

array([1702309.93992612, 2150358.93565827, 3141159.04139051, ...,
       2153546.03508106, 2408968.70355023,  454829.86709001])

In [22]:
y_test

8359    1150000
3844    2100000
3896    3475000
7630     900000
5341    3850000
         ...   
655     1415000
6271    4575000
445     2200000
5687    2695000
660      630000
Name: Price, Length: 1836, dtype: int64

In [23]:
model.score(x_test,y_test)

0.588421088835129